export const cameraTerminology:
  string[] = [
  "APS-C",
  "full frame",
  "Micro Four Thirds",
  "mirrorless",
  "DSLR",
  "autofocus",
  "subject detection",
  "burst rate",
  "image stabilisation",
  "electronic viewfinder",
  "optical viewfinder",
  "dynamic range",
  "ISO",
  "aperture",
  "focal length",
  "shutter speed",
  "shutter count",
  "lens mount",
  "kit lens",
  "prime lens",
  "zoom lens",
];