import type {
  SonyCameraKnowledge,
} from "./types";

export const sonyCameras:
  SonyCameraKnowledge[] = [
    {
      brand: "sony",
      productType: "camera",
      name: "Sony Alpha 1 II",
      slug: "sony-alpha-1-ii",
      family: "Alpha 1",
      aliases: [
        "Sony A1 II",
        "Sony A1II",
        "Sony Alpha 1 II",
        "Sony Alpha 1II",
        "A1 II",
        "A1II",
        "ILCE-1M2",
      ],
      category: "Camera",
      cameraType: "Mirrorless",
      sensorFormat: "Full Frame",
      tier: "Flagship",
      generation: 2,
      releaseYear: 2024,
      megapixels: 50,
      lensMount: "Sony E",
      inBodyStabilisation: true,
      headlineVideo: "8K 30p",
      autofocusSystem:
        "AI-assisted subject recognition autofocus with advanced real-time tracking",
      bestFor: [
        "Professional sports photography",
        "Wildlife photography",
        "High-end hybrid photo and video work",
      ],
      strengths: [
        "High-resolution stacked full-frame sensor",
        "Fast continuous shooting",
        "Advanced AI-assisted autofocus",
        "Strong professional video features",
        "Flagship build quality and controls",
      ],
      limitations: [
        "Very high purchase price",
        "Large files require substantial storage",
        "More camera than most enthusiasts need",
      ],
      summary:
        "Sony's flagship professional mirrorless camera combining high resolution, speed and advanced autofocus.",
    },

    {
      brand: "sony",
      productType: "camera",
      name: "Sony Alpha 7 IV",
      slug: "sony-alpha-7-iv",
      family: "Alpha 7",
      aliases: [
        "Sony A7 IV",
        "Sony A7IV",
        "Sony Alpha 7 IV",
        "Sony Alpha 7IV",
        "A7 IV",
        "A7IV",
        "A74",
        "ILCE-7M4",
      ],
      category: "Camera",
      cameraType: "Mirrorless",
      sensorFormat: "Full Frame",
      tier: "Hybrid",
      generation: 4,
      releaseYear: 2021,
      megapixels: 33,
      lensMount: "Sony E",
      inBodyStabilisation: true,
      headlineVideo: "4K 60p",
      autofocusSystem:
        "Fast hybrid autofocus with real-time eye detection and subject tracking",
      bestFor: [
        "Hybrid photography and video",
        "Weddings and events",
        "Enthusiast content creation",
      ],
      strengths: [
        "Strong 33-megapixel image quality",
        "Reliable autofocus",
        "Good hybrid photo and video performance",
        "Wide Sony E-mount lens selection",
        "Fully articulating screen",
      ],
      limitations: [
        "4K 60p uses an APS-C crop",
        "Rolling shutter can affect fast movement",
        "Burst speed is modest for sports photography",
      ],
      summary:
        "A versatile full-frame hybrid camera designed for both photography and video.",
    },

    {
      brand: "sony",
      productType: "camera",
      name: "Sony Alpha 7R IV",
      slug: "sony-alpha-7r-iv",
      family: "Alpha 7R",
      aliases: [
        "Sony A7R IV",
        "Sony A7RIV",
        "Sony Alpha 7R IV",
        "Sony Alpha 7RIV",
        "A7R IV",
        "A7RIV",
        "A7R4",
        "ILCE-7RM4",
        "ILCE-7RM4A",
      ],
      category: "Camera",
      cameraType: "Mirrorless",
      sensorFormat: "Full Frame",
      tier: "High Resolution",
      generation: 4,
      releaseYear: 2019,
      megapixels: 61,
      lensMount: "Sony E",
      inBodyStabilisation: true,
      headlineVideo: "4K video",
      autofocusSystem:
        "Fast hybrid autofocus with real-time eye autofocus and subject tracking",
      bestFor: [
        "Landscape photography",
        "Studio and commercial photography",
        "High-resolution portrait photography",
        "Architecture and product photography",
      ],
      strengths: [
        "Excellent 61-megapixel image quality",
        "Strong dynamic range",
        "Reliable eye autofocus",
        "High-resolution electronic viewfinder",
        "Good battery life",
      ],
      limitations: [
        "Large image files require substantial storage",
        "Video features trail newer Sony models",
        "Menu system is less refined than later Sony cameras",
        "Rolling shutter can affect fast video movement",
      ],
      summary:
        "A high-resolution full-frame mirrorless camera designed for landscape, studio, commercial and detail-focused photography.",
    },

    {
      brand: "sony",
      productType: "camera",
      name: "Sony Alpha 7R V",
      slug: "sony-alpha-7r-v",
      family: "Alpha 7R",
      aliases: [
        "Sony A7R V",
        "Sony A7RV",
        "Sony Alpha 7R V",
        "Sony Alpha 7RV",
        "A7R V",
        "A7RV",
        "A7R5",
        "ILCE-7RM5",
      ],
      category: "Camera",
      cameraType: "Mirrorless",
      sensorFormat: "Full Frame",
      tier: "High Resolution",
      generation: 5,
      releaseYear: 2022,
      megapixels: 61,
      lensMount: "Sony E",
      inBodyStabilisation: true,
      headlineVideo: "8K 24p",
      autofocusSystem:
        "AI-powered subject recognition autofocus with advanced eye and body tracking",
      bestFor: [
        "Landscape photography",
        "Studio and commercial work",
        "High-detail portrait photography",
      ],
      strengths: [
        "Excellent 61-megapixel image quality",
        "Advanced AI-powered autofocus",
        "Strong in-body stabilisation",
        "High-resolution electronic viewfinder",
        "Flexible multi-angle screen",
      ],
      limitations: [
        "Expensive",
        "Large files demand fast storage and powerful editing hardware",
        "Not designed primarily for high-speed sports shooting",
      ],
      summary:
        "High-resolution full-frame camera aimed at landscape, studio and commercial photographers.",
    },

    {
      brand: "sony",
      productType: "camera",
      name: "Sony Alpha 7S III",
      slug: "sony-alpha-7s-iii",
      family: "Alpha 7S",
      aliases: [
        "Sony A7S III",
        "Sony A7SIII",
        "Sony Alpha 7S III",
        "Sony Alpha 7SIII",
        "A7S III",
        "A7SIII",
        "A7S3",
        "ILCE-7SM3",
      ],
      category: "Camera",
      cameraType: "Mirrorless",
      sensorFormat: "Full Frame",
      tier: "Video Specialist",
      generation: 3,
      releaseYear: 2020,
      megapixels: 12,
      lensMount: "Sony E",
      inBodyStabilisation: true,
      headlineVideo: "4K 120p",
      autofocusSystem:
        "Fast hybrid autofocus with real-time eye detection and touch tracking",
      bestFor: [
        "Professional filmmaking",
        "Low-light video",
        "Documentary and event production",
      ],
      strengths: [
        "Excellent low-light video performance",
        "High-quality 4K 120p recording",
        "Reliable autofocus",
        "Long recording capability",
        "Strong professional video controls",
      ],
      limitations: [
        "Low resolution for detailed still photography",
        "Expensive for photography-focused users",
        "No internal 6K or 8K recording",
      ],
      summary:
        "Professional video-focused mirrorless camera known for excellent low-light performance.",
    },

    {
      brand: "sony",
      productType: "camera",
      name: "Sony Alpha 9 III",
      slug: "sony-alpha-9-iii",
      family: "Alpha 9",
      aliases: [
        "Sony A9 III",
        "Sony A9III",
        "Sony Alpha 9 III",
        "Sony Alpha 9III",
        "A9 III",
        "A9III",
        "A93",
        "ILCE-9M3",
      ],
      category: "Camera",
      cameraType: "Mirrorless",
      sensorFormat: "Full Frame",
      tier: "Professional",
      generation: 3,
      releaseYear: 2023,
      megapixels: 24,
      lensMount: "Sony E",
      inBodyStabilisation: true,
      headlineVideo: "4K 120p",
      autofocusSystem:
        "AI-assisted real-time recognition autofocus with high-speed subject tracking",
      bestFor: [
        "Professional sports photography",
        "Wildlife and action photography",
        "Fast-moving news and event coverage",
      ],
      strengths: [
        "Global shutter eliminates rolling-shutter distortion",
        "Extremely fast burst shooting",
        "Advanced subject tracking",
        "Flash synchronisation at very high shutter speeds",
        "Professional controls and connectivity",
      ],
      limitations: [
        "Very expensive",
        "Lower resolution than high-resolution Sony bodies",
        "Best suited to specialist professional use",
      ],
      summary:
        "Professional sports and wildlife camera featuring a global shutter sensor.",
    },

    {
      brand: "sony",
      productType: "camera",
      name: "Sony Alpha 6700",
      slug: "sony-alpha-6700",
      family: "Alpha 6000",
      aliases: [
        "Sony A6700",
        "Sony Alpha 6700",
        "A6700",
        "ILCE-6700",
      ],
      category: "Camera",
      cameraType: "Mirrorless",
      sensorFormat: "APS-C",
      tier: "Enthusiast",
      generation: 6700,
      releaseYear: 2023,
      megapixels: 26,
      lensMount: "Sony E",
      inBodyStabilisation: true,
      headlineVideo: "4K 120p",
      autofocusSystem:
        "AI-powered subject recognition autofocus with real-time tracking",
      bestFor: [
        "Travel photography",
        "Wildlife and everyday action",
        "Hybrid content creation",
      ],
      strengths: [
        "Advanced subject-recognition autofocus",
        "Compact body",
        "Strong photo and video performance",
        "In-body stabilisation",
        "Broad E-mount lens compatibility",
      ],
      limitations: [
        "Single memory-card slot",
        "Small body can feel cramped with large lenses",
        "4K 120p uses a crop",
      ],
      summary:
        "APS-C hybrid camera offering advanced autofocus and strong video capabilities.",
    },

    {
      brand: "sony",
      productType: "camera",
      name: "Sony FX3",
      slug: "sony-fx3",
      family: "Cinema Line",
      aliases: [
        "Sony FX3",
        "FX3",
        "ILME-FX3",
        "ILME-FX3A",
      ],
      category: "Camera",
      cameraType: "Cinema Camera",
      sensorFormat: "Full Frame",
      tier: "Professional",
      generation: 3,
      releaseYear: 2021,
      megapixels: 12,
      lensMount: "Sony E",
      inBodyStabilisation: true,
      headlineVideo: "4K 120p",
      autofocusSystem:
        "Fast hybrid autofocus with real-time eye detection and touch tracking",
      bestFor: [
        "Professional filmmaking",
        "Run-and-gun video production",
        "Commercial and documentary work",
      ],
      strengths: [
        "Compact cinema-focused body",
        "Excellent low-light performance",
        "Long recording capability with active cooling",
        "Professional audio handle support",
        "Strong autofocus",
      ],
      limitations: [
        "No built-in electronic viewfinder",
        "Low still-photo resolution",
        "More expensive than hybrid alternatives",
      ],
      summary:
        "Compact Cinema Line camera designed for professional filmmakers.",
    },

    {
      brand: "sony",
      productType: "camera",
      name: "Sony ZV-E1",
      slug: "sony-zv-e1",
      family: "ZV",
      aliases: [
        "Sony ZV-E1",
        "Sony ZVE1",
        "ZV-E1",
        "ZVE1",
        "ILCE-ZV-E1",
      ],
      category: "Camera",
      cameraType: "Vlogging Camera",
      sensorFormat: "Full Frame",
      tier: "Creator",
      generation: 1,
      releaseYear: 2023,
      megapixels: 12,
      lensMount: "Sony E",
      inBodyStabilisation: true,
      headlineVideo: "4K 120p",
      autofocusSystem:
        "AI-powered subject recognition autofocus with product showcase and eye tracking",
      bestFor: [
        "Vlogging",
        "Solo content creation",
        "Low-light social video",
      ],
      strengths: [
        "Excellent low-light video quality",
        "Compact full-frame body",
        "Advanced AI-assisted framing tools",
        "Strong autofocus",
        "Useful creator-focused features",
      ],
      limitations: [
        "Can overheat during demanding recording",
        "Low resolution for still photography",
        "No electronic viewfinder",
      ],
      summary:
        "Full-frame creator camera designed for vloggers and online content production.",
    },
  ];